server:
  port: 8080

# Fixer.io API Key Configuration
fixer:
  url: "http://data.fixer.io/api"
  api-key: 052a4123126083f9c812cf977d9af655

scheduler:
  cron: "0 0 * * * ?" # Cron expression for hourly execution
  thread:
    pool:
      size: 4
# Thread pool size



# Spring Data JPA and PostgreSQL Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/currencydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Disable Hibernate's schema auto-generation
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true


# Logging Configuration
logging:
  level:
    root: INFO
    com.example.currencyexchange: DEBUG # Enable debug logs for the application


# Management Endpoints
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: '*'
